apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: example.com
      http:
        paths:
          - path: /echo1
            pathType: Prefix
            backend:
              service:
                name: echo1-srv
                port:
                  number: 80
          - path: /echo2
            pathType: Prefix
            backend:
              service:
                name: echo2-srv
                port:
                  number: 80
    - host: echo1.example.com
      http:
          paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: echo1-srv
                port:
                  number: 80
    - host: echo2.example.com
      http:
          paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: echo2-srv
                port:
                  number: 80